[package]
name = "reator"
version = "0.1.0"
authors = ["Elves Sousa <elves.sousa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
